-- MySQL Script generated by MySQL Workbench
-- 03/25/15 18:19:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema iithcourses
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema iithcourses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iithcourses` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `iithcourses` ;

-- -----------------------------------------------------
-- Table `iithcourses`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iithcourses`.`Department` (
  `Short_Name` VARCHAR(5) NOT NULL,
  `Full_Name` VARCHAR(45) NOT NULL,
  `Website` VARCHAR(60) NULL,
  PRIMARY KEY (`Short_Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iithcourses`.`Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iithcourses`.`Instructor` (
  `Instructor_ID` INT NOT NULL AUTO_INCREMENT,
  `Instructor_Name` VARCHAR(45) NOT NULL,
  `Instructor_Credentials` VARCHAR(45) NOT NULL,
  `Department_Short_Name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Instructor_ID`),
  INDEX `fk_Instructor_Department_idx` (`Department_Short_Name` ASC),
  CONSTRAINT `fk_Instructor_Department`
    FOREIGN KEY (`Department_Short_Name`)
    REFERENCES `iithcourses`.`Department` (`Short_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iithcourses`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iithcourses`.`Courses` (
  `Course_ID` CHAR(6) NOT NULL,
  `Course_Title` VARCHAR(45) NOT NULL,
  `Credits` INT NOT NULL,
  `Department_Short_Name` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`Course_ID`),
  INDEX `fk_Courses_Department1_idx` (`Department_Short_Name` ASC),
  CONSTRAINT `fk_Courses_Department1`
    FOREIGN KEY (`Department_Short_Name`)
    REFERENCES `iithcourses`.`Department` (`Short_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iithcourses`.`Offered_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iithcourses`.`Offered_Courses` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Semester` INT NOT NULL,
  `Year` INT NOT NULL,
  `Start_Date` INT NOT NULL DEFAULT 1,
  `End_Date` INT NOT NULL DEFAULT 6,
  `Num_Student` INT NULL,
  `Courses_Course_ID` CHAR(6) NOT NULL,
  `Instructor_Instructor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Offered_Courses_Courses1_idx` (`Courses_Course_ID` ASC),
  INDEX `fk_Offered_Courses_Instructor1_idx` (`Instructor_Instructor_ID` ASC),
  CONSTRAINT `fk_Offered_Courses_Courses1`
    FOREIGN KEY (`Courses_Course_ID`)
    REFERENCES `iithcourses`.`Courses` (`Course_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offered_Courses_Instructor1`
    FOREIGN KEY (`Instructor_Instructor_ID`)
    REFERENCES `iithcourses`.`Instructor` (`Instructor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iithcourses`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `iithcourses`.`Schedule` (
  `Room_Number` INT NOT NULL,
  `Slot` INT NOT NULL,
  `Day_Of_Week` INT NOT NULL,
  `Offered_Courses_ID` INT NOT NULL,
  PRIMARY KEY (`Room_Number`, `Slot`, `Day_Of_Week`),
  INDEX `fk_Schedule_Offered_Courses1_idx` (`Offered_Courses_ID` ASC),
  CONSTRAINT `fk_Schedule_Offered_Courses1`
    FOREIGN KEY (`Offered_Courses_ID`)
    REFERENCES `iithcourses`.`Offered_Courses` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
