-- MySQL Script generated by MySQL Workbench
-- 03/25/15 00:27:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `Short_Name` CHAR(5) NOT NULL,
  `Full_Name` VARCHAR(45) NOT NULL,
  `Website` VARCHAR(60) NULL,
  PRIMARY KEY (`Short_Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instructor` (
  `Instructor_ID` INT NOT NULL,
  `Instructor_Name` VARCHAR(45) NOT NULL,
  `Instructor_Credentials` VARCHAR(45) NOT NULL,
  `Department_Short_Name` CHAR(5) NOT NULL,
  PRIMARY KEY (`Instructor_ID`, `Department_Short_Name`),
  INDEX `fk_Instructor_Department1_idx` (`Department_Short_Name` ASC),
  CONSTRAINT `fk_Instructor_Department1`
    FOREIGN KEY (`Department_Short_Name`)
    REFERENCES `mydb`.`Department` (`Short_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `Course_ID` CHAR(6) NOT NULL,
  `Course_Title` VARCHAR(45) NOT NULL,
  `Credits` VARCHAR(45) NULL,
  PRIMARY KEY (`Course_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department_has_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department_has_Courses` (
  `Department_Short_Name` CHAR(5) NOT NULL,
  `Courses_Course_ID` CHAR(6) NOT NULL,
  PRIMARY KEY (`Department_Short_Name`, `Courses_Course_ID`),
  INDEX `fk_Department_has_Courses_Courses1_idx` (`Courses_Course_ID` ASC),
  INDEX `fk_Department_has_Courses_Department1_idx` (`Department_Short_Name` ASC),
  CONSTRAINT `fk_Department_has_Courses_Department1`
    FOREIGN KEY (`Department_Short_Name`)
    REFERENCES `mydb`.`Department` (`Short_Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Department_has_Courses_Courses1`
    FOREIGN KEY (`Courses_Course_ID`)
    REFERENCES `mydb`.`Courses` (`Course_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Offered_Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Offered_Courses` (
  `ID` INT NOT NULL,
  `Semester` INT NOT NULL,
  `Year` INT NOT NULL,
  `Start_Date` DATE NOT NULL,
  `End_Date` DATE NOT NULL,
  `Num_Student` INT NOT NULL,
  `Courses_Course_ID` CHAR(6) NOT NULL,
  `Instructor_Instructor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Courses_Course_ID`, `Instructor_Instructor_ID`),
  INDEX `fk_Offered_Courses_Courses1_idx` (`Courses_Course_ID` ASC),
  INDEX `fk_Offered_Courses_Instructor1_idx` (`Instructor_Instructor_ID` ASC),
  CONSTRAINT `fk_Offered_Courses_Courses1`
    FOREIGN KEY (`Courses_Course_ID`)
    REFERENCES `mydb`.`Courses` (`Course_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Offered_Courses_Instructor1`
    FOREIGN KEY (`Instructor_Instructor_ID`)
    REFERENCES `mydb`.`Instructor` (`Instructor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `Room_Number` INT NOT NULL,
  `Slot` INT NOT NULL,
  `Day_Of_Week` INT NOT NULL,
  `Offered_Courses_ID` INT NOT NULL,
  `Offered_Courses_Courses_Course_ID` CHAR(6) NOT NULL,
  `Offered_Courses_Instructor_Instructor_ID` INT NOT NULL,
  PRIMARY KEY (`Room_Number`, `Slot`, `Day_Of_Week`, `Offered_Courses_ID`, `Offered_Courses_Courses_Course_ID`, `Offered_Courses_Instructor_Instructor_ID`),
  INDEX `fk_Schedule_Offered_Courses1_idx` (`Offered_Courses_ID` ASC, `Offered_Courses_Courses_Course_ID` ASC, `Offered_Courses_Instructor_Instructor_ID` ASC),
  CONSTRAINT `fk_Schedule_Offered_Courses1`
    FOREIGN KEY (`Offered_Courses_ID` , `Offered_Courses_Courses_Course_ID` , `Offered_Courses_Instructor_Instructor_ID`)
    REFERENCES `mydb`.`Offered_Courses` (`ID` , `Courses_Course_ID` , `Instructor_Instructor_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
